name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install Flask
        run : |
          python -m pip install flask
      - name: Install Redis module
        run: pip install redis


      - name: Navigate to backend directory
        run: cd backend
      - name: Run script
        run: python3 /home/runner/work/4A_SQR_Gabriel_Romeo_Cloud-Computing/4A_SQR_Gabriel_Romeo_Cloud-Computing/backend/tweet.py check_syntax
